### PR TITLE
Use bucket.yml.sample to step around git stuff

### PR DESCRIPTION
**Pull request by dgw**
Instead of storing bucket.yml in the repo, where it might possibly clobber a user's settings if they do something stupid with git, store a sample file and include copying/renaming that file in the install instructions.

.gitignore actual bucket.yml.

### CODE REVIEW

**Comment by zigdon** [comment]
Wouldn't git refuse to clobber local changes, instead offering to merge changes? Much better UI than trying to figure out what has changed with an update?

**Comment by dgw** [comment]
It's still possible to accidentally overwrite `bucket.yml` by, say, running a hard `git reset` without thinking. Git will just overwrite all your changes without prompting if you do that.

**Comment by zigdon** [comment]
I think there's only so much we can do to protect users from themselves. I
think losing the ability to merge upstream config changes is worse than the
clobber chance.

The best solution, of course, is to move a lot of what in that's yml file
to the DB, and keep just what we need to get to the DB in there.

**Comment by dgw** [comment]
I can see that logic, and moving config data into the database (maybe a new `bucket_config` table?) would be a good long-term thing. I'm going to have to learn more Perl to do so, but I'd like to help with that.

If the config file contains just the bare minimum data, would it then be OK to make this change?

**Comment by zigdon** [comment]
Yeah, if all it had was the DB connection creds, I think removing it from
being tracked in the repo would make sense.

**Comment by dgw** [comment]
Cool. I created issue #54 to hash out what, exactly, would be left in the config file. Meanwhile I hope it's OK to leave this PR open for eventual merging. Cheers!

**Comment by dgw** [comment]
Ironically, updating my production instance was rather tedious due to this being merged. But it's the last time there will be any possibility of git refusing to pull due to local config changes, so that's a good silver lining.

**Pull request merged**
