### PR TITLE
Make "remove value band" work immediately

### PR DESCRIPTION
**Pull request by dgw**
Tested minimally, but should work. Let me know if there are code style issues or something like that.

### CODE REVIEW

**Comment by dgw** [comment]
Yes, this is a kludge around how deleting values works.

**Comment by dgw** [comment]
Just curious, is there any reason this hasn't been merged? Haven't seen any issues running my bot with it for the last 3 months.

**Comment by zigdon** [comment]
No reason, I just have been somewhat busy.

How does this change relate to remove values?

**Comment by dgw** [comment]
I didn't touch that one, since this change seemed to eliminate those times when "remove value band" would fail on just-added values. Do you want me to look at that code and possibly amend this before merging?

**Comment by zigdon** [comment]
Sure, go for it.

**Comment by dgw** [comment]
This should probably just get merged. I haven't noticed any newly added values I couldn't remove in weeks.

**Pull request merged**
